[webservers]
192.168.155.131 ansible_user=root ansible_password=Ironman@01 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[docker]
10.10.10.108 ansible_user=root ansible_password=Ironman@01 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
